name: Update Block Domain List

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest domain list from Google Sheets
        run: |
          # Replace with your published CSV URL from Google Sheets
          GOOGLE_SHEET_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vSkX9AJGUrc2svr9zPPGKXM-01TTBWyLDv4MvasLFhLynFWoW2k-TACOrRedm86Td9gCq87W-8jawmQ/pub?gid=1932785084&single=true&output=csv"
          curl -sS "$GOOGLE_SHEET_URL" -o domain_list.csv

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add blocklist.csv
            git commit -m "Update domain list from Google Sheets - $(date '+%Y%m%d %H:%M')"
            git push
          else
            echo "No changes detected."
          fi
